version: '3'
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - redis
    environment:
      DB_PORT: 3306
      DB_HOST: mysql
      REDIS_PORT: 6379
      REDIS_HOST: redis
  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - redis
    environment:
      DB_PORT: 3306
      DB_HOST: mysql
      REDIS_PORT: 6379
      REDIS_HOST: redis
    tty: true
  mysql:
    image: mysql:5.7.22
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: participant
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: homestead
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "33061:3306"
  redis:
    image: redis:3.0
    ports:
      - "63791:6379"
  node:
    image: node:12.7-alpine
    volumes:
      - ./:/var/www
    working_dir: /var/www
